# Generated by Django 2.2.5 on 2019-10-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=111)),
                ('desc', models.CharField(max_length=111)),
                ('date', models.IntegerField()),
            ],
        ),
    ]
